# Copyright 2023-Present Couchbase, Inc.
#
# Use of this software is governed by the Business Source License included in
# the file licenses/BSL-Couchbase.txt.  As of the Change Date specified in that
# file, in accordance with the Business Source License, use of this software
# will be governed by the Apache License, Version 2.0, included in the file
# licenses/APL2.txt.

version: 2
registries:
  github:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.GH_PERSONAL_ACCESS_TOKEN_CBROBOTSG}}
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    registries: "*"
    schedule:
      interval: "weekly"
