# Copyright 2026-Present Couchbase, Inc.
#
# Use of this software is governed by the Business Source License included
# in the file licenses/BSL-Couchbase.txt.  As of the Change Date specified
# in that file, in accordance with the Business Source License, use of this
# software will be governed by the Apache License, Version 2.0, included in
# the file licenses/APL2.txt.

# Maps GitHub usernames to Slack member IDs (Slack profile -> More -> Copy member ID),
# so Jenkins can DM the commit author on E2E build results.
DragosPetruTaraban: "U0221MMQKJ9"
JRascagneres: "UC51SKA66"
RIT3shSapata: "U04EQ6XLSF5"
adamcfraser: "U03DMET9D"
bbrks: "UAVMTSQ02"
borrrden: "U03DAHVP9"
gregns1: "U03LW9MNHLP"
syncgatewaybot-alerts: "C0BHQLWP7UL"
syncgatewaybot: "CCCKUSYLR"
torcolvin: "U03D1N4373N"
vipbhardwaj: "U04ESPQSPU4"
