version: "2"
linters:
  enable:
    - gocritic # The most opinionated Go source code linter
    #- goprintffuncname # Checks that printf-like functions are named with `f` at the end
    #- gosec # Inspects source code for security problems
    #- gosimple # (megacheck) Linter for Go source code that specializes in simplifying a code
    - govet # (vet, vetshadow) Vet examines Go source code and reports suspicious constructs, such as Printf calls whose arguments do not align with the format string
    - ineffassign # Detects when assignments to existing variables are not used
    - misspell # Finds commonly misspelled English words in comments
    #- nakedret # Finds naked returns in functions greater than a specified function length
    #- prealloc # Finds slice declarations that could potentially be preallocated
    #- revive # Golint differs from gofmt. Gofmt reformats Go source code, whereas golint prints out style mistakes
    - staticcheck # (megacheck) Staticcheck is a go vet on steroids, applying a ton of static analysis checks
    - unconvert # Remove unnecessary type conversions
    #- unparam # Reports unused function parameters
    - unused # (megacheck) Checks Go code for unused constants, variables, functions and types
  settings:
    gocritic:
      enabled-checks:
        - ruleguard
      disabled-checks:
        - appendAssign
        - assignOp
        - badCond
        - captLocal
        - commentFormatting
        - deprecatedComment
        - elseif
        - ifElseChain
        - regexpMust
        - singleCaseSwitch
        - sloppyLen
        - unlambda
        - valSwap
        - wrapperFunc
      settings:
        ruleguard:
          failOn: all
          rules: ${base-path}/ruleguard/rules-*.go
  exclusions:
    generated: strict
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      # Disable goconst in test files, often we have duplicated strings across tests, but don't make sense as constants.
      - linters:
          - goconst
        # cover _testing.go (utility testing files) and _test.go files
        # base/util_testing.go / rest/utilities_testing\.*.go
        path: (_test.*\.go)
      - linters:
          - unused
        path: rest/debug.go
formatters:
  enable:
    - goimports
  exclusions:
    generated: strict
