# Copyright 2022-Present Couchbase, Inc.
#
# Use of this software is governed by the Business Source License included in
# the file licenses/BSL-Couchbase.txt.  As of the Change Date specified in that
# file, in accordance with the Business Source License, use of this software
# will be governed by the Apache License, Version 2.0, included in the file
# licenses/APL2.txt.

# This configuration file is read by the Redocly `openapi` CLI tool to validate/lint our specs (from GitHub Actions)

apis:
  admin:
    root: "./docs/api/admin.yaml"
    decorators:
      remove-x-internal: on
  admin-internal:
    root: "./docs/api/admin.yaml"
  admin-capella:
    root: "./docs/api/admin-capella.yaml"
    decorators:
      plugin/excise-rbac-capella: on
      filter-out:
        property: x-capella
        value: false
      remove-x-internal: on
  public:
    root: "./docs/api/public.yaml"
    decorators:
      remove-x-internal: on
  public-internal:
    root: "./docs/api/public.yaml"
  public-capella:
    root: "./docs/api/public.yaml"
    decorators:
      filter-out:
        property: x-capella
        value: false
      info-override:
        description: "App Services manages access and synchronization between Couchbase Lite and Couchbase Capella"
        title: "App Services"
      plugin/excise-rbac-capella: on
      plugin/replace-description-capella: on
      plugin/replace-server-capella:
        serverUrl: 'https://{hostname}:4984'
      remove-x-internal: on
  metric:
    root: "./docs/api/metric.yaml"
    decorators:
      remove-x-internal: on
  metric-internal:
    root: "./docs/api/metric.yaml"
  metric-capella:
    root: "./docs/api/metric-capella.yaml"
    decorators:
      filter-out:
        property: x-capella
        value: false
      plugin/excise-rbac-capella: on
      plugin/replace-description-capella: on
      remove-x-internal: on
  diagnostic:
    root: "./docs/api/diagnostic.yaml"
    decorators:
      remove-x-internal: on
  diagnostic-internal:
    root: "./docs/api/diagnostic.yaml"

plugins:
  - './docs/api/plugins/plugin.js'

extends:
  - minimal
rules:
  # disable unnecessary/invalid warnings
  operation-2xx-response: off # _blipsync 101 Upgrade ...
  operation-summary: off      # Optional field
  no-ambiguous-paths: off     # /{db}/{doc} != /_debug/expvar
  no-identical-paths: off     # /{db} != /{targetdb}
  no-path-trailing-slash: off # Some endpoints require a trailing slash
  security-defined: off       # TODO: Denote public and authenticated API endpoints with https://redocly.com/docs/cli/rules/security-defined
