package sync_gateway

import (
	"fmt"
	"strings"
)

var (
	MOBILE = "/mobile"
	MOBILE_CONFIG = fmt.Sprintf("%s/config", MOBILE)
	MOBILE_CONFIG_SERVER = fmt.Sprintf("%s/server", MOBILE_CONFIG)
	MOBILE_CONFIG_DATABASES = fmt.Sprintf("%s/databases", MOBILE_CONFIG)
)

var (
	MOBILE_SERVICE_HOST_PORT = "localhost:50052"

	// TODO: use same UUID as generated by CBGT
	GATEWAY_UUID = "123"

	// Discover this from OS -- just a convenience to help give a hint, since otherwise users just see an opaque UUID
	GATEWAY_HOSTNAME = "localhost"

)

func AddTrailingSlash(initial string) string {
	if strings.HasSuffix(initial, "/") {
		return initial
	}
	return fmt.Sprintf("%s/", initial)
}

func init() {

}