package sync_gateway

const (
	DefaultPublicInterface = "0.0.0.0"
	DefaultAdminInterface  = "127.0.0.1"
	DefaultPublicPort      = 4984
	DefaultAdminPort       = 4985
)

var (

	// TODO: use same UUID as generated by CBGT
	GATEWAY_UUID = "123"

	// Discover this from OS -- just a convenience to help give a hint, since otherwise users just see an opaque UUID
	GATEWAY_HOSTNAME = "localhost"
)
