global:
  scrape_interval:     5s
  evaluation_interval: 5s

rule_files:
  - '/etc/prometheus/rules/*'

scrape_configs:
  - job_name: swg
    metrics_path: /_metrics
    static_configs:
      - targets:
          - sync_gateway:4986
