# /{db}/_oidc_testing/.well-known-openid-configuration
parameters:
- $ref: ../../components/parameters.yaml#/db
get:
  summary: OpenID Connect mock provider
  description: Mock an OpenID Connect provider response for testing purposes. This
    returns a response that is the same structure as what Sync Gateway expects from
    an OIDC provider after initiating OIDC authentication.
  responses:
    "200":
      description: 'Successfully generated OpenID Connect provider mock response. '
      headers:
        Expiry:
          schema:
            type: string
          description: the time until the response expires.
      content:
        application/json:
          schema:
            type: object
            properties:
              issuer:
                type: string
              authorization_endpoint:
                type: string
              token_endpoint:
                type: string
              jwks_uri:
                type: string
              userinfo_endpoint:
                type: string
              id_token_signing_alg_values_supported:
                type: string
              response_types_supported:
                type: string
              subject_types_supported:
                type: string
              scopes_supported:
                type: string
              claims_supported:
                type: string
              token_endpoint_auth_methods_supported:
                type: string
    "403":
      $ref: ../../components/responses.yaml#/OIDC-test-provider-disabled
    "404":
      $ref: ../../components/responses.yaml#/Not-found
  tags:
  - OpenID Connect
