#!/usr/bin/env python

import optparse
import xml.etree.ElementTree as ET
import urllib2
import sys
import os
import subprocess

# This script makes it easy to use "go get" in conjunction with a repo manifest xml
# which pins dependencies at certain commits.
#
# To view the "delta" between your GOPATH repos latest commit and corresponding manifest entries:
#
#   ./manifest-helper -d
#
# To update all repositories in your GOPATH listed in the manifest to the commit from the corresponding manifest entries:
#
#   ./manifest-helper -u
#
# To reset all repositories in your GOPATH listed in the manifest to their latest master branch commit (useful if you need to rerun go get -u):
#
#   ./manifest-helper -r 
#
ignored_repos = [
    "build",
    "sync_gateway",
    "sync-gateway-accel"
]

def parse_args():
    """
    Parse command line args and return a tuple
    """
    parser = optparse.OptionParser()
    parser.add_option(
        '-d',
        '--display-deltas',
        default=False,
        action="store_true",
        help='For all repos in the manifest that are also in the GOPATH, display the delta between what commit it is on versus what is in the manifest'
    )
    parser.add_option(
        '-u',
        '--update-to-manifest-commit',
        default=False,
        action="store_true",
        help='Update any repos in the GOPATH to a DETACHED HEAD that matches the commit specified in the manifest for that repo'
    )
    parser.add_option(
        '-r',
        '--update-to-master-commit',
        default=False,
        action="store_true",
        help='For all repos in the manifest that are also in the GOPATH, run git checkout master.  May be needed if you want to run go get.'
    )
    (opts, args) = parser.parse_args()
    return (parser, opts.update_to_manifest_commit, opts.display_deltas, opts.update_to_master_commit)

def display_commit_delta(path, manifest_revision, gopath_revision):
    if manifest_revision != gopath_revision:
        print("{} {}: manifest: {} gopath repo: {}".format(
            "** DELTA DETECTED **",
            path,
            manifest_revision,
            gopath_revision,
        ))
    else:
        print("{} {} ({})".format(
            "Up-to-date",
            path,
            manifest_revision,
        ))

def git_checkout_manifest_commit(path, manifest_revision, gopath_revision):
    
    # first run a git diff to make sure there are no local changes
    output = subprocess.check_output(
        ["git", "diff"],
        cwd=path
    )
    if len(output) > 0:
        print("Git diff output: {}".format(output))
        raise Exception("It appears you have local changes in {}.  You should stash or reset to HEAD".format(path))

    # run git fetch to avoid "fatal: reference is not a tree" errors
    print("git fetch in {}".format(path))
    output = subprocess.check_output(
        ["git", "fetch"],
        cwd=path
    )
    
    print("git checkout {} in {}".format(manifest_revision, path))
    output = subprocess.check_output(
        ["git", "checkout", manifest_revision],
        cwd=path
    )
    print("git checkout {} output: {}".format(manifest_revision, output))

def git_checkout_master(path, manifest_revision, gopath_revision):

    print("git checkout master in {}".format(path))
    output = subprocess.check_output(
        ["git", "checkout", "master"],
        cwd=path
    )
    print("git checkout master output: {}".format(output))

    
def process_commit_deltas(tree, callback):
   root = tree.getroot()
   for element in root:
       if element.tag != "project":
           continue
       project_name = element.get("name")
       if project_name in ignored_repos:
           print("Skipping: {}".format(project_name))
           continue
       manifest_revision = element.get("revision")
       path = element.get("path")
       path = remove_godeps_prefix(path)
       path = os.path.join(
           os.environ["GOPATH"],
           path
       )
       
       gopath_revision = get_gopath_revision(path)
       if gopath_revision is None:
           continue
       callback(
           path,
           manifest_revision,
           gopath_revision
       )

       
def get_gopath_revision(path):

    """
    Given a path like "godeps/src/github.com/couchbase/cb-heartbeat",
    run 'git rev-parse HEAD' in the corresponding GOPATH directory
    and return the current commit
    """

    if not os.path.exists(path):
        print("WARN: Directory does not exist, skipping: {}".format(path))
        return None
    
    latest_commit = subprocess.check_output(
        ["git", "rev-parse", "HEAD"],
        cwd=path
    )
    return latest_commit.strip()


def remove_godeps_prefix(path):

    """
    Strip the leading "godeps" off the path.

    Given "godeps/src/github.com/couchbase/cb-heartbeat"
    Return "src/github.com/couchbase/cb-heartbeat"
    """
    return os.path.relpath(path, 'godeps')


def path_to_manifest():
    """
    Discover the path to the manifest XML based on the $GOPATH
    """
    path = os.environ["GOPATH"]
    
    path_components = [
        "src",
        "github.com",
        "couchbase",
        "sync_gateway",
        "manifest",
        "default.xml"
    ]
    for path_component in path_components:
        path = os.path.join(path, path_component)

    return path


if __name__=="__main__":

    if not "GOPATH" in os.environ:
        raise Exception("You must define a GOPATH environment variable")
    
    # get arguments
    (parser, update_to_manifest_commit, display_deltas, update_to_master_commit) = parse_args()
   
    # fetch manifest content and parse xml
    manifest = path_to_manifest()
    print("Processing manifest: {}".format(manifest))
    tree = ET.ElementTree(file=open(manifest))

    if display_deltas:
        callback_func=display_commit_delta
        process_commit_deltas(tree, callback_func)

    if update_to_manifest_commit:
        callback_func=git_checkout_manifest_commit
        process_commit_deltas(tree, callback_func)

    if update_to_master_commit:
        callback_func=git_checkout_master
        process_commit_deltas(tree, callback_func)
