# Copyright 2022-Present Couchbase, Inc.
#
# Use of this software is governed by the Business Source License included
# in the file licenses/BSL-Couchbase.txt.  As of the Change Date specified
# in that file, in accordance with the Business Source License, use of this
# software will be governed by the Apache License, Version 2.0, included in
# the file licenses/APL2.txt.

openapi: 3.0.3
info:
  title: Sync Gateway
  description: Sync Gateway manages access and synchronization between Couchbase Lite and Couchbase Server
  version: 3.1.0
  license:
    name: Business Source License 1.1 (BSL)
    url: 'https://github.com/couchbase/sync_gateway/blob/master/LICENSE'
servers:
  - url: 'https://{hostname}:4985'
    description: Admin API
    variables:
      hostname:
        description: The hostname to use
        default: localhost
paths:
  '/{db}/_session':
    $ref: './paths/admin/db-_session.yaml'
    x-capella: true
  '/{db}/_session/{sessionid}':
    $ref: './paths/admin/db-_session-sessionid.yaml'
  '/{db}/_user/{name}':
    $ref: './paths/admin/db-_user-name.yaml'
  '/{db}/_user/{name}/_session':
    $ref: './paths/admin/db-_user-name-_session.yaml'
  '/{db}/_user/{name}/_session/{sessionid}':
    $ref: './paths/admin/db-_user-name-_session-sessionid.yaml'
  '/{db}/_role/':
    $ref: './paths/admin/db-_role-.yaml'
  '/{db}/_role/{name}':
    $ref: './paths/admin/db-_role-name.yaml'

externalDocs:
  description: Manage App Services for Mobile and Edge | Couchbase Docs
  url: 'https://docs.couchbase.com/cloud/app-services/index.html'
