# Copyright 2022-Present Couchbase, Inc.
#
# Use of this software is governed by the Business Source License included
# in the file licenses/BSL-Couchbase.txt.  As of the Change Date specified
# in that file, in accordance with the Business Source License, use of this
# software will be governed by the Apache License, Version 2.0, included in
# the file licenses/APL2.txt.

openapi: 3.0.3
info:
  title: Sync Gateway Metrics REST API
  description: |-
    # Introduction

    Sync Gateway manages access and synchronization between Couchbase Lite and Couchbase Server.
    The Sync Gateway Metrics REST API returns Sync Gateway metrics, in JSON or Prometheus-compatible formats, for performance monitoring and diagnostic purposes.
  version: '3.3'
  license:
    name: Business Source License 1.1 (BSL)
    url: 'https://github.com/couchbase/sync_gateway/blob/master/LICENSE'
servers:
  - url: '{protocol}://{hostname}:4986'
    description: Metrics API
    variables:
      protocol:
        description: The protocol to use (HTTP or HTTPS)
        default: http
        enum:
          - http
          - https
      hostname:
        description: The hostname to use
        default: localhost
paths:
  /_ping:
    $ref: ./paths/common/_ping.yaml
  /_metrics:
    $ref: ./paths/metric/metrics.yaml
    x-internal: true
  /metrics:
    $ref: ./paths/metric/metrics.yaml
  /_expvar:
    $ref: ./paths/metric/_expvar.yaml
    tags:
      - JSON
tags:
  - name: Prometheus
    description: Endpoints for use with Prometheus
  - name: JSON
    description: Endpoints for use with JSON metrics
  - name: Server
    description: Endpoints for managing the REST API
externalDocs:
  description: ⬆️ Metrics REST API Overview
  url: rest-api-metrics.html
