# Copyright 2022-Present Couchbase, Inc.
#
# Use of this software is governed by the Business Source License included
# in the file licenses/BSL-Couchbase.txt.  As of the Change Date specified
# in that file, in accordance with the Business Source License, use of this
# software will be governed by the Apache License, Version 2.0, included in
# the file licenses/APL2.txt.

openapi: 3.0.3
info:
  title: Sync Gateway Public REST API
  description: |-
    # Introduction

    Sync Gateway manages access and synchronization between Couchbase Lite and Couchbase Server.
    The Sync Gateway Public REST API is used for client replication.
  version: '3.3'
  license:
    name: Business Source License 1.1 (BSL)
    url: 'https://github.com/couchbase/sync_gateway/blob/master/LICENSE'
servers:
  - url: '{protocol}://{hostname}:4984'
    description: Public API
    variables:
      protocol:
        description: The protocol to use (HTTP or HTTPS)
        default: http
        enum:
          - http
          - https
      hostname:
        description: The hostname to use
        default: localhost
paths:
  '/{db}/_session':
    $ref: './paths/public/db-_session.yaml'
  '/{db}/':
    $ref: './paths/public/db-.yaml'
  /:
    $ref: ./paths/public/-.yaml
  /_ping:
    $ref: ./paths/common/_ping.yaml
  '/{keyspace}/':
    $ref: './paths/admin/keyspace-.yaml'
  '/{db}/_design/{ddoc}':
    $ref: './paths/public/db-_design-ddoc.yaml'
    x-capella: false
  '/{db}/_design/{ddoc}/_view/{view}':
    $ref: './paths/public/db-_design-ddoc-_view-view.yaml'
    x-capella: false
  '/{keyspace}/{docid}':
    $ref: './paths/public/keyspace-docid.yaml'
  '/{keyspace}/{docid}/{attach}':
    $ref: './paths/public/keyspace-docid-attach.yaml'
  '/{keyspace}/_changes':
    $ref: './paths/public/keyspace-_changes.yaml'
  '/{keyspace}/_all_docs':
    $ref: './paths/public/keyspace-_all_docs.yaml'
  '/{keyspace}/_bulk_docs':
    $ref: './paths/public/keyspace-_bulk_docs.yaml'
  '/{keyspace}/_bulk_get':
    $ref: './paths/public/keyspace-_bulk_get.yaml'
  '/{keyspace}/_local/{docid}':
    $ref: './paths/public/keyspace-_local-docid.yaml'
  '/{keyspace}/_revs_diff':
    $ref: './paths/public/keyspace-_revs_diff.yaml'
  '/{db}/_oidc':
    $ref: './paths/public/db-_oidc.yaml'
  '/{db}/_oidc_challenge':
    $ref: './paths/public/db-_oidc_challenge.yaml'
  '/{db}/_oidc_callback':
    $ref: './paths/public/db-_oidc_callback.yaml'
  '/{db}/_oidc_refresh':
    $ref: './paths/public/db-_oidc_refresh.yaml'
  '/{db}/_oidc_testing/.well-known/openid-configuration':
    $ref: './paths/common/db-_oidc_testing-.well-known-openid-configuration.yaml'
    x-capella: false
  '/{db}/_oidc_testing/authorize':
    $ref: './paths/common/db-_oidc_testing-authorize.yaml'
    x-capella: false
  '/{db}/_oidc_testing/token':
    $ref: './paths/common/db-_oidc_testing-token.yaml'
    x-capella: false
  '/{db}/_oidc_testing/certs':
    $ref: './paths/common/db-_oidc_testing-certs.yaml'
    x-capella: false
  '/{db}/_oidc_testing/authenticate':
    $ref: './paths/common/db-_oidc_testing-authenticate.yaml'
    x-capella: false
  '/{db}/_blipsync':
    $ref: './paths/public/db-_blipsync.yaml'
  # couchdb compatibility, put at the end to show at bottom
  '/{targetdb}/':
    $ref: './paths/public/targetdb-.yaml'
  # deprecated endpoints, put at the end to show up at the bottom
  '/{db}/_facebook':
    $ref: './paths/public/db-_facebook.yaml'
    x-capella: false
  '/{db}/_google':
    $ref: './paths/public/db-_google.yaml'
    x-capella: false
  '/{db}/_ensure_full_commit':
    $ref: './paths/common/db-_ensure_full_commit.yaml'
tags:
  - name: Server
    description: Manage server activities
  - name: Database Management
    description: Create and manage Sync Gateway databases
  - name: Session
    description: Manage user sessions
  - name: Authentication
    description: Manage OpenID Connect Authentication
  - name: Document
    description: Create and manage documents
  - name: Document Attachment
    description: Create and manage document attachments
  - name: Replication
    description: Create and manage inter-Sync Gateway replications
    x-capella: false
  - name: Unsupported
    description: Endpoints that are not supported by Sync Gateway
    x-capella: false
externalDocs:
  description: ⬆️ Public REST API Overview
  url: rest-api.html
