name: Go

on:
  pull_request:
    branches:
      - 'master'
      - 'release/*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    # Checkout the commit that caused the action to run.
    # We'll bootstrap for dependencies, but use this copy of the SG code.
    - uses: actions/checkout@v2

    # Bootstrap (dependencies)
    # Note: Copying bootstrap.sh because it won't run from the same directory as main.go
    - name: Bootstrap
      run: |
        mkdir -p .sgdeps
        cp bootstrap.sh .sgdeps/
        cd .sgdeps
        chmod +x bootstrap.sh
        ./bootstrap.sh -c ${{ github.event.pull_request.head.sha }}

    - name: Set GOPATH
      run: |
        echo "GOPATH=${GITHUB_WORKSPACE}/.sgdeps/godeps" >> $GITHUB_ENV

    # Lint
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.34
        only-new-issues: true

# Only Go need if running tests, golangci-lint doesn't need it...
#     - name: Set up Go 1.13.4
#       uses: actions/setup-go@v2
#       with:
#         go-version: ^1.13.4
