# Copyright 2022-Present Couchbase, Inc.
#
# Use of this software is governed by the Business Source License included in
# the file licenses/BSL-Couchbase.txt.  As of the Change Date specified in that
# file, in accordance with the Business Source License, use of this software
# will be governed by the Apache License, Version 2.0, included in the file
# licenses/APL2.txt.

name: service
permissions:
  contents: read

on:
  push:
    # Only run when we modify service files
    paths:
      - 'service/**'
      - 'integration-test/**'
      - '.github/workflows/service.yml'
    branches:
      - 'main'
      - 'release/*'
      - 'feature/*'
      - 'beryllium'
      - 'CBG*'
      - 'ci-*'
      - 'api-ci-*'
  pull_request:
    # Only run when we modify service files
    paths:
      - 'service/**'
      - 'integration-test/**'
    branches:
      - 'main'
      - 'release/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'release/')}}

jobs:
  scripts:
    runs-on: ubuntu-latest
    name: Verify service script installation.
    steps:
      - uses: actions/checkout@v4
      # build sync gateway since the executable is needed for service installation
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.3
      - name: "Build Sync Gateway"
        run: mkdir -p ./bin && go build -o ./bin ./...
      - name: "Run test scripts"
        run: ./integration-test/service-install-tests.sh
