# Copyright 2022-Present Couchbase, Inc.
#
# Use of this software is governed by the Business Source License included in
# the file licenses/BSL-Couchbase.txt.  As of the Change Date specified in that
# file, in accordance with the Business Source License, use of this software
# will be governed by the Apache License, Version 2.0, included in the file
# licenses/APL2.txt.

name: service

on:
  push:
    # Only run when we modify service files
    paths:
      - 'service/**'
      - 'integration-test/**'
    branches:
      - 'main'
      - 'release/*'
      - 'feature/*'
      - 'beryllium'
      - 'CBG*'
      - 'ci-*'
      - 'api-ci-*'
  pull_request:
    # Only run when we modify service files
    paths:
      - 'service/**'
      - 'integration-test/**'
    branches:
      - 'main'
      - 'release/*'

jobs:
  scripts:
    runs-on: ubuntu-latest
    name: Verify service script installation.
    steps:
      - uses: actions/checkout@v4
      - name: "Run test scripts"
        run: ./integration-test/service-install-tests.sh
