# Copyright 2022-Present Couchbase, Inc.
#
# Use of this software is governed by the Business Source License included in
# the file licenses/BSL-Couchbase.txt.  As of the Change Date specified in that
# file, in accordance with the Business Source License, use of this software
# will be governed by the Apache License, Version 2.0, included in the file
# licenses/APL2.txt.

name: service

on:
  push:
    # Only run when we modify service files
    paths:
      - 'service/**'
      - 'integration-test/**'
    branches:
      - 'main'
      - 'release/*'
      - 'feature/*'
      - 'beryllium'
      - 'CBG*'
      - 'ci-*'
      - 'api-ci-*'
  pull_request:
    # Only run when we modify service files
    paths:
      - 'service/**'
      - 'integration-test/**'
    branches:
      - 'main'
      - 'release/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'release/')}}

env:
  # Pinned action versions, referenced by the steps below through their YAML anchors.
  ACTIONS_CHECKOUT_VERSION: &actions_checkout_version actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
  ACTIONS_SETUP_GO_VERSION: &actions_setup_go_version actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5

jobs:
  scripts:
    runs-on: ubuntu-latest
    name: Verify service script installation.
    steps:
      - uses: *actions_checkout_version
      # build sync gateway since the executable is needed for service installation
      - uses: *actions_setup_go_version
        with:
          go-version: 1.25.14
      - name: "Build Sync Gateway"
        run: mkdir -p ./bin && go build -o ./bin ./...
      - name: "Run test scripts"
        run: ./integration-test/service-install-tests.sh
